apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: public_test1
  annotations:
    github.com/project-slug: backstagete/public_test1
spec:
  type: other
  lifecycle: unknown
  owner: CNCF
